### ISSUE TITLE
missing explicit link to pthread

### ISSUE THREAD

**Issue by ycollet** [x42/robtk#3]
On fedora 23, compilation stops because of a missing explicit link to pthread.

**Comment by x42** [comment]
Compilation of which plugin(s) or applications?

robtk itself is a header only include SDK.  There is nothing to compile or link.
Do you have a compiler log?  I hazard a guess it may be a jack app using it that fails.

**Comment by ycollet** [comment]
Sorry, I thought in a first place that it was related to robtk.
I built x42-plugins.
Here is the last message from the log:

g++  -g -Wall -Wno-unused-function -DHAVE_LV2_1_8 -I. `pkg-config --cflags glu` -DHAVE_IDLE_IFACE -g -Wall -Wno-unused-function -DHAVE_LV2_1_8 -I. -DXTERNAL_UI `pkg-config --cflags lv2` -fPIC -msse -msse2 -mfpmath=sse -ffast-math -fomit-frame-pointer -O3 -fno-finite-math-only -DNDEBUG -DVERSION="\"0.6.4\"" `pkg-config --cflags cairo pango`  -DUSE_GUI_THREAD \
  -DUINQHACK="145667898314124" \
  -DPLUGIN_SOURCE="\"gui/sisco.c\"" \
  -o build/siscoUI_gl.so ../robtk/ui_gl.c \
  ../robtk/pugl/pugl_x11.c \
  zita-resampler/resampler.cc zita-resampler/resampler-table.cc \
  -shared -Wl,-Bstatic -Wl,-Bdynamic -Wl,--as-needed  -lX11 `pkg-config  --libs cairo pangocairo pango glu gl` 
strip -s build/siscoUI_gl.so
g++  -g -Wall -Wno-unused-function -DHAVE_LV2_1_8 -I. -msse -msse2 -mfpmath=sse -ffast-math -fomit-frame-pointer -O3 -fno-finite-math-only -DNDEBUG -DVERSION="\"0.6.4\""  `pkg-config --cflags jack lv2 pango pangocairo glu gl` -DDEFAULT_NOT_ONTOP \
  -DXTERNAL_UI -DHAVE_IDLE_IFACE \
  -DRTK_DESCRIPTOR="lv2ui_descriptor" \
  -DPLUGIN_SOURCE="\"gui/sisco.c\"" \
  -DJACK_DESCRIPT="\"lv2ttl/jack_4chan.h\"" \
  -DAPPNAME="\"scope\"" \
  -o build/x42-scope \
  ../robtk/jackwrap.c ../robtk/ui_gl.c ../robtk/pugl/pugl_x11.c   \
  zita-resampler/resampler.cc zita-resampler/resampler-table.cc src/sisco.c \
   -lm `pkg-config  --libs pangocairo glu gl` -lX11 `pkg-config  --libs cairo pangocairo pango glu gl`   `pkg-config  --libs jack`
/usr/bin/ld: /tmp/cc0GHSWp.o: référence au symbole non défini «pthread_create@@GLIBC_2.2.5»
/usr/lib64/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: erreur: ld a retourné 1 code d'état d'exécution
../robtk/robtk.mk:124: recipe for target 'build/x42-scope' failed
make[1]: *** [build/x42-scope] Error 1
make[1]: Leaving directory '/home/collette/repositories/Gareus/x42-plugins/sisco.lv2'
Makefile:16: recipe for target 'sisco.lv2' failed
make: *** [sisco.lv2] Error 2


$ git remote -v
origin  https://github.com/x42/x42-plugins.git (fetch)
origin  https://github.com/x42/x42-plugins.git (push)

**Comment by x42** [comment]
Thanks,  and you're right it's probably best to fix this /centrally/ in robtk.mk

It's odd though: `pkg-config ... jack` should pull in pthread (jack requires uses it as well) via cflags `-pthread` or libs `-lpthread`.
