### ISSUE TITLE
Please change your submodule references to https

### ISSUE THREAD

**Issue by darix** [x42/robtk#7]
```
Fetching submodule robtk
fatal: unable to connect to github.com:
github.com[0: 140.82.121.3]: errno=Connection timed out
```

I think the git:// protocl got deprecated

**Comment by x42** [comment]
I believe this was already done years ago. Which parent repository is still affected by this?

**Comment by darix** [comment]
I tried "git pull" against dpl e.g. and it still tried to fetch the git:// references. I will just do clean checkouts for all plugins. wanted to work on updating my packages. fresh working copies for all work.
